name: Ruby

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      fail-fast: false
      matrix:
        ruby: ['2.7', '3.0', '3.1']
        gemfile: [Gemfile.ar-6.1, Gemfile.ar-7.0, Gemfile.ar-master]
        timezone_aware: [0, 1]
    env:
      BUNDLE_GEMFILE: gemfiles/${{ matrix.gemfile }}
      TIMEZONE_AWARE: ${{ matrix.timezone_aware }}
      POSTGRES: 1
      MYSQL: 1
      POSTGRES_JSON: 1
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: typed_store
          POSTGRES_PASSWORD: typed_store
          POSTGRES_DB: typed_store_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
      mysql:
        image: mysql:8.0.21
        env:
          MYSQL_USER: typed_store
          MYSQL_PASSWORD: typed_store
          MYSQL_DATABASE: typed_store_test
        ports:
          - 3306:3306
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Ruby Tests
        run: bundle exec rake
